name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      cutr: ${{ steps.filter.outputs.cutr }}
      echor: ${{ steps.filter.outputs.echor }}
      findr: ${{ steps.filter.outputs.findr }}
      grepr: ${{ steps.filter.outputs.grepr }}
      headr: ${{ steps.filter.outputs.headr }}
      uniqr: ${{ steps.filter.outputs.uniqr }}
      wcr: ${{ steps.filter.outputs.wcr }}
      commr: ${{ steps.filter.outputs.commr }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            cutr:
              - 'cutr/**'
            echor:
              - 'echor/**'
            findr:
              - 'findr/**'
            grepr:
              - 'grepr/**'
            headr:
              - 'headr/**'
            uniqr:
              - 'uniqr/**'
            wcr:
              - 'wcr/**'
            commr:
              - 'commr/**'
  build:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - cutr
          - echor
          - findr
          - grepr
          - headr
          - uniqr
          - wcr
          - commr
    steps:
      - uses: actions/checkout@v4
        if: needs.detect-changes.outputs[matrix.project] == 'true'
      - name: Build ${{ matrix.project }}
        if: needs.detect-changes.outputs[matrix.project] == 'true'
        run: cd ${{ matrix.project }} && cargo build --verbose
      - name: Run tests for ${{ matrix.project }}
        if: needs.detect-changes.outputs[matrix.project] == 'true'
        run: cd ${{ matrix.project }} && cargo test --verbose
